### PR TITLE
fix: alt ip container overflow

### LINKED ISSUE #139: Show less button overflows when a probe has many alt ips
Image

### PR DESCRIPTION
**Pull request by PavelKopecky**
Closes #139

### CODE REVIEW

File: app/components/ShowMore.vue [hunk 1]
```diff
@@ -14,6 +14,9 @@
 	const wrapperHeight = ref('auto');
 	const initialWrapperHeight = ref('auto');
 	const isExpanding = ref(false);
+	const { width: containerWidth } = useElementSize(wrapperRef);
+	const { width: windowWidth } = useWindowSize();
```
Comment (MartinKolarik) [inline app/components/ShowMore.vue:18]: Is this actually needed? It seems that if we watch the container size, watching the window size might be unnecessary; the `onResize` logic could be based on the container size.

Comment (PavelKopecky) [reply app/components/ShowMore.vue:18]: As discussed, explanation comment here https://github.com/jsdelivr/globalping-dash/pull/143/commits/8da0d9384ea2a2e1dbfe3fa3e9bd565c2a80b6de. Also renamed the onResize param https://github.com/jsdelivr/globalping-dash/pull/143/commits/7e265f9044703fa441e2c887f4eb025d0dd5e793.
